GET http://localhost:3000/api/journals/12/entries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJmbHllcjEwNTkiLCJpYXQiOjE3ODY1NTIxMDIsImV4cCI6MTc4NjYzODUwMn0.oj5sYbndrqr-xRHTj8mELe5EPyd-acTLDy7Xm-WCACI
