DELETE http://localhost:3000/api/journals/9/entries/21
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJHllcjEwNTkiLCJpYXQiOjE3ODY1NTIxMDIsImV4cCI6MTc4NjYzODUwMn0.oj5sYbndrqr-xRHTj8mELe5EPyd-acTLDy7Xm-WCACI
